language: node_js
sudo: true
node_js:
  - '10.16'
git:
  submodules: false
cache:
  directories:
    - /*/**/node_modules
before_install:
  - git submodule update --init --remote --recursive
install:
  # - yarn bootstrap
  - travis_retry make ci-install
before_script:
  - npm install -g terser
script:
  - npx lerna run --ignore cita-web-debugger build
  - yarn test
